_BASE_: "Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    NUM_CLASSES: 2
SOLVER:
  STEPS: (60277, 71759)
  MAX_ITER: 77500
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 2500
  BASE_LR: 0.005
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
DATASETS:
  TRAIN: ("caltech_pedestrians_train",)
  TEST: ("tju-pedestrian-traffic_test",)
OUTPUT_DIR: 