_BASE_: "Base-RCNN-C4.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "Res5ROIHeads"
    NUM_CLASSES: 2
SOLVER:
  STEPS: (52500, 62500)
  MAX_ITER: 67500
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
DATASETS:
  TRAIN: ("tju-pedestrian-traffic_train",)
  TEST: ("caltech_pedestrians_test",)
